config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/tdviet4free/fedcloudclient:
      branch: sqaaas-test
      repo: https://github.com/tdviet4free/fedcloudclient
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-dandelion-hamster.sh
        container: qc.acc_chummy-celadon-markhor
  QC.Doc:
    repos:
      github.com/tdviet4free/fedcloudclient find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-pear-weasel.sh
        container: qc.doc_droopy-carmine-octopus
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-corn-hippopotamus.sh
        container: qc.doc_snappy-rust-clam
      github.com/tdviet4free/fedcloudclient markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-champagne-armadillo.sh
        container: qc.doc_shaky-brass-dalmatian
      github.com/tdviet4free/fedcloudclient restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-lilac-wolfhound.sh
        container: qc.doc_snazzy-malachite-hyena
  QC.Lic:
    repos:
      github.com/tdviet4free/fedcloudclient licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-green-snail.sh
        container: qc.lic_woolly-zucchini-dogfish
  QC.Met:
    repos:
      github.com/tdviet4free/fedcloudclient validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-amethyst-chameleon.sh
        container: qc.met_wheezy-azure-tetra
  QC.Sec:
    repos:
      github.com/tdviet4free/fedcloudclient bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-ultramarine-mammoth.sh
        container: qc.sec_woozy-periwinkle-shrimp
  QC.Sty:
    repos:
      github.com/tdviet4free/fedcloudclient flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-linen-armadillo.sh
        container: qc.sty_lumpy-buff-beaver
      github.com/tdviet4free/fedcloudclient hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-amaranth-mist.sh
        container: qc.sty_sickly-amaranth-dormouse
      github.com/tdviet4free/fedcloudclient jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-vermilion-mandrill.sh
        container: qc.sty_leaky-cobalt-beetle
  QC.Ver:
    repos:
      github.com/tdviet4free/fedcloudclient get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-tomato-bee.sh
        container: qc.ver_surly-white-indri
timeout: 1800
