config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/tdviet/fedcloudclient:
      branch: master
      repo: https://github.com/tdviet/fedcloudclient
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/tdviet/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-green-corgi.sh
        container: qc.acc_stuffy-pear-insect
  QC.Doc:
    repos:
      github.com/tdviet/fedcloudclient find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cardinal-hyena.sh
        container: qc.doc_gummy-vermilion-tamarin
      github.com/tdviet/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-champagne-maltese.sh
        container: qc.doc_chummy-lemon-gorilla
      github.com/tdviet/fedcloudclient markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cardinal-shrimp.sh
        container: qc.doc_wiggy-magenta-greyhound
      github.com/tdviet/fedcloudclient restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-chocolate-bobcat.sh
        container: qc.doc_foggy-periwinkle-bat
  QC.Lic:
    repos:
      github.com/tdviet/fedcloudclient licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-apricot-dolphin.sh
        container: qc.lic_cloudy-grey-lizard
  QC.Sec:
    repos:
      github.com/tdviet/fedcloudclient bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-corn-kudu.sh
        container: qc.sec_skinny-apricot-meerkat
  QC.Sty:
    repos:
      github.com/tdviet/fedcloudclient flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-charcoal-maltese.sh
        container: qc.sty_snoopy-azure-terrier
      github.com/tdviet/fedcloudclient hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-smalt-impala.sh
        container: qc.sty_silly-sapphire-giraffe
      github.com/tdviet/fedcloudclient jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-aquamarine-cichlid.sh
        container: qc.sty_lovely-beige-beaver
  QC.Ver:
    repos:
      github.com/tdviet/fedcloudclient get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-copper-sparrow.sh
        container: qc.ver_sleepy-pumpkin-hyrax
timeout: 1800
