config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/tdviet/fedcloudclient:
      branch: master
      repo: https://github.com/tdviet/fedcloudclient
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/tdviet/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-violet-buzzard.sh
        container: qc.acc_dorky-red-wombat
  QC.Doc:
    repos:
      github.com/tdviet/fedcloudclient find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-taupe-chinook.sh
        container: qc.doc_dorky-chocolate-bracke
      github.com/tdviet/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-beige-stingray.sh
        container: qc.doc_cheeky-green-monster
      github.com/tdviet/fedcloudclient markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-purple-uakari.sh
        container: qc.doc_homey-eggplant-chamois
      github.com/tdviet/fedcloudclient restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-mauve-beaver.sh
        container: qc.doc_crappy-razzmatazz-avocet
  QC.Lic:
    repos:
      github.com/tdviet/fedcloudclient licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-chartreuse-zorse.sh
        container: qc.lic_shabby-harlequin-buffalo
  QC.Sec:
    repos:
      github.com/tdviet/fedcloudclient bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-pumpkin-bongo.sh
        container: qc.sec_randy-magenta-anteater
  QC.Sty:
    repos:
      github.com/tdviet/fedcloudclient flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-emerald-snake.sh
        container: qc.sty_hasty-lilac-ant
  QC.Ver:
    repos:
      github.com/tdviet/fedcloudclient get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-bistre-millipede.sh
        container: qc.ver_smelly-green-labradoodle
timeout: 1800
