config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/tdviet4free/fedcloudclient:
      branch: sqaaas-test
      repo: https://github.com/tdviet4free/fedcloudclient
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-olive-rottweiler.sh
        container: qc.acc_sleazy-auburn-schnauzer
  QC.Doc:
    repos:
      github.com/tdviet4free/fedcloudclient find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-sapphire-tapir.sh
        container: qc.doc_fuzzy-turquoise-meerkat
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lime-crab.sh
        container: qc.doc_slaphappy-platinum-chamois
      github.com/tdviet4free/fedcloudclient markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-periwinkle-bonobo.sh
        container: qc.doc_slimy-turquoise-drever
      github.com/tdviet4free/fedcloudclient restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-linen-sheep.sh
        container: qc.doc_gloppy-rust-falcon
  QC.Lic:
    repos:
      github.com/tdviet4free/fedcloudclient licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-wisteria-angelfish.sh
        container: qc.lic_stinky-myrtle-woodlouse
  QC.Sec:
    repos:
      github.com/tdviet4free/fedcloudclient bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-charcoal-millipede.sh
        container: qc.sec_surly-magnolia-chameleon
  QC.Sty:
    repos:
      github.com/tdviet4free/fedcloudclient flake8:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-asparagus-opossum.sh
        container: qc.sty_wheezy-amethyst-frise
      github.com/tdviet4free/fedcloudclient hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-magenta-guppy.sh
        container: qc.sty_wheezy-cyan-robin
      github.com/tdviet4free/fedcloudclient jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-coral-barnacle.sh
        container: qc.sty_hilly-bronze-quail
  QC.Ver:
    repos:
      github.com/tdviet4free/fedcloudclient get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-corn-dog.sh
        container: qc.ver_sickly-fuchsia-oyster
timeout: 1800
